spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${dbuser}
    password: ${dbpassword}
    driver-class-name: org.postgresql.Driver
    #url: jdbc-secretsmanager:postgresql://localhost:5432/postgres
    #driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
    #username: appsecret
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  config:
    import: aws-secretsmanager:dbsecret
  mvc:
    converters:
      preferred-json-mapper: gson
  # can use this to set default date-format
  #gson:
  #  date-format: dd/MM/yyyy

server:
  port: 8082

aws:
  secretsmanager:
    enabled: true
    endpoint: http://localhost:4566
